#!/bin/bash
#
# Start squeezeboxserver
#
echo "Starting Lyrion Music Server..."
sleep 5
squeezeboxserver --u "$SLIMUSER" --prefsdir /config/prefs --logdir /config/logs --cachedir /config/cache --httpport 9000
